window.onload = function () {

    const words = [
        
        { ru: "день", gender: "2", audio: "../audio/день.mp3" },
        { ru: "неделя", gender: "1", audio: "../audio/неделя.mp3" },
        { ru: "минута", gender: "1", audio: "../audio/минута.mp3" },
        { ru: "окно", gender: "2", audio: "../audio/окно.mp3" },
        { ru: "ночь", gender: "3", audio: "../audio/ночь.mp3" },
        {"ru": "человек", "gender": "2", "audio": "../audio/человек.mp3"},
{"ru": "мужчина", "gender": "1", "audio": "../audio/мужчина.mp3"},
{"ru": "женщина", "gender": "1", "audio": "../audio/женщина.mp3"},
{"ru": "жизнь", "gender": "3", "audio": "../audio/жизнь.mp3"},
{"ru": "смерть", "gender": "3", "audio": "../audio/смерть.mp3"},
{"ru": "папа", "gender": "1", "audio": "../audio/папа.mp3"},
{"ru": "мама", "gender": "1", "audio": "../audio/мама.mp3"},
{"ru": "отец", "gender": "2", "audio": "../audio/отец.mp3"},
{"ru": "мать", "gender": "3", "audio": "../audio/мать.mp3"},
{"ru": "ребёнок", "gender": "2", "audio": "../audio/ребёнок.mp3"},
{"ru": "младенец", "gender": "2", "audio": "../audio/младенец.mp3"},
{"ru": "потомство", "gender": "2", "audio": "../audio/потомство.mp3"},
{"ru": "сын", "gender": "2", "audio": "../audio/сын.mp3"},
{"ru": "дочь", "gender": "3", "audio": "../audio/дочь.mp3"},
{"ru": "пасынок", "gender": "2", "audio": "../audio/пасынок.mp3"},
{"ru": "падчерица", "gender": "1", "audio": "../audio/падчерица.mp3"},
{"ru": "брат", "gender": "2", "audio": "../audio/брат.mp3"},
{"ru": "близнец", "gender": "2", "audio": "../audio/близнец.mp3"},
{"ru": "сестра", "gender": "1", "audio": "../audio/сестра.mp3"},
{"ru": "дедушка", "gender": "1", "audio": "../audio/дедушка.mp3"},
{"ru": "бабушка", "gender": "1", "audio": "../audio/бабушка.mp3"},
{"ru": "внук", "gender": "2", "audio": "../audio/внук.mp3"},
{"ru": "внучка", "gender": "1", "audio": "../audio/внучка.mp3"},
{"ru": "дядя", "gender": "1", "audio": "../audio/дядя.mp3"},
{"ru": "тётя", "gender": "1", "audio": "../audio/тётя.mp3"},
{"ru": "отчим", "gender": "2", "audio": "../audio/отчим.mp3"},
{"ru": "мачеха", "gender": "1", "audio": "../audio/мачеха.mp3"},
{"ru": "родственник", "gender": "2", "audio": "../audio/родственник.mp3"},
{"ru": "родственница", "gender": "1", "audio": "../audio/родственница.mp3"},
{"ru": "семья", "gender": "1", "audio": "../audio/семья.mp3"},
{"ru": "имя", "gender": "2", "audio": "../audio/имя.mp3"},
{"ru": "отчество", "gender": "2", "audio": "../audio/отчество.mp3"},
{"ru": "фамилия", "gender": "1", "audio": "../audio/фамилия.mp3"},
{"ru": "помолвка", "gender": "1", "audio": "../audio/помолвка.mp3"},
{"ru": "свадьба", "gender": "1", "audio": "../audio/свадьба.mp3"},
{"ru": "жених", "gender": "2", "audio": "../audio/жених.mp3"},
{"ru": "невеста", "gender": "1", "audio": "../audio/невеста.mp3"},
{"ru": "брак", "gender": "2", "audio": "../audio/брак.mp3"},
{"ru": "муж", "gender": "2", "audio": "../audio/муж.mp3"},
{"ru": "жена", "gender": "1", "audio": "../audio/жена.mp3"},
{"ru": "зять", "gender": "2", "audio": "../audio/зять.mp3"},
{"ru": "невестка", "gender": "1", "audio": "../audio/невестка.mp3"},
{"ru": "свёкор", "gender": "2", "audio": "../audio/свёкор.mp3"},
{"ru": "тесть", "gender": "2", "audio": "../audio/тесть.mp3"},
{"ru": "свекровь", "gender": "3", "audio": "../audio/свекровь.mp3"},
{"ru": "тёща", "gender": "1", "audio": "../audio/тёща.mp3"},
{"ru": "деверь", "gender": "2", "audio": "../audio/деверь.mp3"},
{"ru": "развод", "gender": "2", "audio": "../audio/развод.mp3"},
{"ru": "тело", "gender": "2", "audio": "../audio/тело.mp3"},
{"ru": "голова", "gender": "1", "audio": "../audio/голова.mp3"},
{"ru": "лицо", "gender": "2", "audio": "../audio/лицо.mp3"},
{"ru": "лоб", "gender": "2", "audio": "../audio/лоб.mp3"},
{"ru": "бровь", "gender": "3", "audio": "../audio/бровь.mp3"},
{"ru": "веко", "gender": "2", "audio": "../audio/веко.mp3"},
{"ru": "глаз", "gender": "2", "audio": "../audio/глаз.mp3"},
{"ru": "зрачок", "gender": "2", "audio": "../audio/зрачок.mp3"},
{"ru": "щека", "gender": "1", "audio": "../audio/щека.mp3"},
{"ru": "нос", "gender": "2", "audio": "../audio/нос.mp3"},
{"ru": "ухо", "gender": "2", "audio": "../audio/ухо.mp3"},
{"ru": "рот", "gender": "2", "audio": "../audio/рот.mp3"},
{"ru": "губа", "gender": "1", "audio": "../audio/губа.mp3"},
{"ru": "язык", "gender": "2", "audio": "../audio/язык.mp3"},
{"ru": "десна", "gender": "1", "audio": "../audio/десна.mp3"},
{"ru": "зуб", "gender": "2", "audio": "../audio/зуб.mp3"},
{"ru": "борода", "gender": "1", "audio": "../audio/борода.mp3"},
{"ru": "шея", "gender": "1", "audio": "../audio/шея.mp3"},
{"ru": "горло", "gender": "2", "audio": "../audio/горло.mp3"},
{"ru": "голос", "gender": "2", "audio": "../audio/голос.mp3"},
{"ru": "плечо", "gender": "2", "audio": "../audio/плечо.mp3"},
{"ru": "рука", "gender": "1", "audio": "../audio/рука.mp3"},
{"ru": "локоть", "gender": "2", "audio": "../audio/локоть.mp3"},
{"ru": "запястье", "gender": "2", "audio": "../audio/запястье.mp3"},
{"ru": "ладонь", "gender": "3", "audio": "../audio/ладонь.mp3"},
{"ru": "кулак", "gender": "2", "audio": "../audio/кулак.mp3"},
{"ru": "палец", "gender": "2", "audio": "../audio/палец.mp3"},
{"ru": "ноготь", "gender": "2", "audio": "../audio/ноготь.mp3"},
{"ru": "грудь", "gender": "3", "audio": "../audio/грудь.mp3"},
{"ru": "спина", "gender": "1", "audio": "../audio/спина.mp3"},
{"ru": "бедро", "gender": "2", "audio": "../audio/бедро.mp3"},
{"ru": "нога", "gender": "1", "audio": "../audio/нога.mp3"},
{"ru": "колено", "gender": "2", "audio": "../audio/колено.mp3"},
{"ru": "лодыжка", "gender": "1", "audio": "../audio/лодыжка.mp3"},
{"ru": "пятка", "gender": "1", "audio": "../audio/пятка.mp3"},
{"ru": "кость", "gender": "3", "audio": "../audio/кость.mp3"},
{"ru": "ребро", "gender": "2", "audio": "../audio/ребро.mp3"},
{"ru": "сердце", "gender": "2", "audio": "../audio/сердце.mp3"},
{"ru": "печень", "gender": "3", "audio": "../audio/печень.mp3"},
{"ru": "желудок", "gender": "2", "audio": "../audio/желудок.mp3"},
{"ru": "кровь", "gender": "3", "audio": "../audio/кровь.mp3"},
{"ru": "здоровье", "gender": "2", "audio": "../audio/здоровье.mp3"},
{"ru": "болезнь", "gender": "3", "audio": "../audio/болезнь.mp3"},
{"ru": "кашель", "gender": "2", "audio": "../audio/кашель.mp3"},
{"ru": "насморк", "gender": "2", "audio": "../audio/насморк.mp3"},
{"ru": "температура", "gender": "1", "audio": "../audio/температура.mp3"},
{"ru": "давление", "gender": "2", "audio": "../audio/давление.mp3"},
{"ru": "боль", "gender": "3", "audio": "../audio/боль.mp3"},
{"ru": "рана", "gender": "1", "audio": "../audio/рана.mp3"},
{"ru": "перелом", "gender": "2", "audio": "../audio/перелом.mp3"},
{"ru": "лекарство", "gender": "2", "audio": "../audio/лекарство.mp3"},
{"ru": "одежда", "gender": "1", "audio": "../audio/одежда.mp3"},
{"ru": "шапка", "gender": "1", "audio": "../audio/шапка.mp3"},
{"ru": "рубашка", "gender": "1", "audio": "../audio/рубашка.mp3"},
{"ru": "пиджак", "gender": "2", "audio": "../audio/пиджак.mp3"},
{"ru": "костюм", "gender": "2", "audio": "../audio/костюм.mp3"},
{"ru": "форма", "gender": "1", "audio": "../audio/форма.mp3"},
{"ru": "халат", "gender": "2", "audio": "../audio/халат.mp3"},
{"ru": "платье", "gender": "2", "audio": "../audio/платье.mp3"},
{"ru": "ремень", "gender": "2", "audio": "../audio/ремень.mp3"},
{"ru": "шуба", "gender": "1", "audio": "../audio/шуба.mp3"},
{"ru": "обувь", "gender": "3", "audio": "../audio/обувь.mp3"},
{"ru": "пуговица", "gender": "1", "audio": "../audio/пуговица.mp3"},
{"ru": "карман", "gender": "2", "audio": "../audio/карман.mp3"},
{"ru": "ткань", "gender": "3", "audio": "../audio/ткань.mp3"},
{"ru": "шёлк", "gender": "2", "audio": "../audio/шёлк.mp3"},
{"ru": "хлопок", "gender": "2", "audio": "../audio/хлопок.mp3"},
{"ru": "лён", "gender": "2", "audio": "../audio/лён.mp3"},
{"ru": "шерсть", "gender": "3", "audio": "../audio/шерсть.mp3"},
{"ru": "дом", "gender": "2", "audio": "../audio/дом.mp3"},
{"ru": "жильё", "gender": "2", "audio": "../audio/жильё.mp3"},
{"ru": "дворец", "gender": "2", "audio": "../audio/дворец.mp3"},
{"ru": "шатёр", "gender": "2", "audio": "../audio/шатёр.mp3"},
{"ru": "квартира", "gender": "1", "audio": "../audio/квартира.mp3"},
{"ru": "стена", "gender": "1", "audio": "../audio/стена.mp3"},
{"ru": "дверь", "gender": "3", "audio": "../audio/дверь.mp3"},
{"ru": "окно", "gender": "2", "audio": "../audio/окно.mp3"},
{"ru": "пол", "gender": "2", "audio": "../audio/пол.mp3"},
{"ru": "потолок", "gender": "2", "audio": "../audio/потолок.mp3"},
{"ru": "крыша", "gender": "1", "audio": "../audio/крыша.mp3"},
{"ru": "подвал", "gender": "2", "audio": "../audio/подвал.mp3"},
{"ru": "этаж", "gender": "2", "audio": "../audio/этаж.mp3"},
{"ru": "лестница", "gender": "1", "audio": "../audio/лестница.mp3"},
{"ru": "замок", "gender": "2", "audio": "../audio/замок.mp3"},
{"ru": "ключ", "gender": "2", "audio": "../audio/ключ.mp3"},
{"ru": "гараж", "gender": "2", "audio": "../audio/гараж.mp3"},
{"ru": "комната", "gender": "1", "audio": "../audio/комната.mp3"},
{"ru": "кухня", "gender": "1", "audio": "../audio/кухня.mp3"},
{"ru": "спальня", "gender": "1", "audio": "../audio/спальня.mp3"},
{"ru": "библиотека", "gender": "1", "audio": "../audio/библиотека.mp3"},
{"ru": "склад", "gender": "2", "audio": "../audio/склад.mp3"},
{"ru": "туалет", "gender": "2", "audio": "../audio/туалет.mp3"},
{"ru": "мебель", "gender": "3", "audio": "../audio/мебель.mp3"},
{"ru": "стол", "gender": "2", "audio": "../audio/стол.mp3"},
{"ru": "стул", "gender": "2", "audio": "../audio/стул.mp3"},
{"ru": "шкаф", "gender": "2", "audio": "../audio/шкаф.mp3"},
{"ru": "гардероб", "gender": "2", "audio": "../audio/гардероб.mp3"},
{"ru": "полка", "gender": "1", "audio": "../audio/полка.mp3"},
{"ru": "кровать", "gender": "3", "audio": "../audio/кровать.mp3"},
{"ru": "диван", "gender": "2", "audio": "../audio/диван.mp3"},
{"ru": "кресло", "gender": "2", "audio": "../audio/кресло.mp3"},
{"ru": "вешалка", "gender": "1", "audio": "../audio/вешалка.mp3"},
{"ru": "лампа", "gender": "1", "audio": "../audio/лампа.mp3"},
{"ru": "зеркало", "gender": "2", "audio": "../audio/зеркало.mp3"},
{"ru": "расчёска", "gender": "1", "audio": "../audio/расчёска.mp3"},
{"ru": "бритва", "gender": "1", "audio": "../audio/бритва.mp3"},
{"ru": "мыло", "gender": "2", "audio": "../audio/мыло.mp3"},
{"ru": "шампунь", "gender": "2", "audio": "../audio/шампунь.mp3"},
{"ru": "одеяло", "gender": "2", "audio": "../audio/одеяло.mp3"},
{"ru": "простыня", "gender": "1", "audio": "../audio/простыня.mp3"},
{"ru": "подушка", "gender": "1", "audio": "../audio/подушка.mp3"},
{"ru": "полотенце", "gender": "2", "audio": "../audio/полотенце.mp3"},
{"ru": "занавеска", "gender": "1", "audio": "../audio/занавеска.mp3"},
{"ru": "ковёр", "gender": "2", "audio": "../audio/ковёр.mp3"},
{"ru": "зонт", "gender": "2", "audio": "../audio/зонт.mp3"},
{"ru": "чайник", "gender": "2", "audio": "../audio/чайник.mp3"},
{"ru": "кастрюля", "gender": "1", "audio": "../audio/кастрюля.mp3"},
{"ru": "сковорода", "gender": "1", "audio": "../audio/сковорода.mp3"},
{"ru": "миска", "gender": "1", "audio": "../audio/миска.mp3"},
{"ru": "половник", "gender": "2", "audio": "../audio/половник.mp3"},
{"ru": "тарелка", "gender": "1", "audio": "../audio/тарелка.mp3"},
{"ru": "ложка", "gender": "1", "audio": "../audio/ложка.mp3"},
{"ru": "вилка", "gender": "1", "audio": "../audio/вилка.mp3"},
{"ru": "нож", "gender": "2", "audio": "../audio/нож.mp3"},
{"ru": "душ", "gender": "2", "audio": "../audio/душ.mp3"},
{"ru": "ванна", "gender": "1", "audio": "../audio/ванна.mp3"},
{"ru": "бассейн", "gender": "2", "audio": "../audio/бассейн.mp3"},
{"ru": "раковина", "gender": "1", "audio": "../audio/раковина.mp3"},
{"ru": "холодильник", "gender": "2", "audio": "../audio/холодильник.mp3"},
{"ru": "пылесос", "gender": "2", "audio": "../audio/пылесос.mp3"},
{"ru": "утюг", "gender": "2", "audio": "../audio/утюг.mp3"},
{"ru": "вентилятор", "gender": "2", "audio": "../audio/вентилятор.mp3"},
{"ru": "кондиционер", "gender": "2", "audio": "../audio/кондиционер.mp3"},
{"ru": "плита", "gender": "1", "audio": "../audio/плита.mp3"},
{"ru": "микроволновка", "gender": "1", "audio": "../audio/микроволновка.mp3"},
{"ru": "тостер", "gender": "2", "audio": "../audio/тостер.mp3"},
{"ru": "телевизор", "gender": "2", "audio": "../audio/телевизор.mp3"},
{"ru": "телефон", "gender": "2", "audio": "../audio/телефон.mp3"},
{"ru": "радио", "gender": "2", "audio": "../audio/радио.mp3"},
{"ru": "сад", "gender": "2", "audio": "../audio/сад.mp3"},
{"ru": "цветок", "gender": "2", "audio": "../audio/цветок.mp3"},
{"ru": "дерево", "gender": "2", "audio": "../audio/дерево.mp3"},
{"ru": "трава", "gender": "1", "audio": "../audio/трава.mp3"},
{"ru": "ремонт", "gender": "2", "audio": "../audio/ремонт.mp3"},
{"ru": "уборка", "gender": "1", "audio": "../audio/уборка.mp3"},
{"ru": "стирка", "gender": "1", "audio": "../audio/стирка.mp3"},
{"ru": "мусор", "gender": "2", "audio": "../audio/мусор.mp3"},
{"ru": "салфетка", "gender": "1", "audio": "../audio/салфетка.mp3"},
{"ru": "тряпка", "gender": "1", "audio": "../audio/тряпка.mp3"},
{"ru": "ведро", "gender": "2", "audio": "../audio/ведро.mp3"},
{"ru": "таз", "gender": "2", "audio": "../audio/таз.mp3"},
{"ru": "веник", "gender": "2", "audio": "../audio/веник.mp3"},
{"ru": "совок", "gender": "2", "audio": "../audio/совок.mp3"},
{"ru": "швабра", "gender": "1", "audio": "../audio/швабра.mp3"},
{"ru": "порошок", "gender": "2", "audio": "../audio/порошок.mp3"},
{"ru": "пила", "gender": "1", "audio": "../audio/пила.mp3"},
{"ru": "молоток", "gender": "2", "audio": "../audio/молоток.mp3"},
{"ru": "отвёртка", "gender": "1", "audio": "../audio/отвёртка.mp3"},
{"ru": "документ", "gender": "2", "audio": "../audio/документ.mp3"},
{"ru": "бумага", "gender": "1", "audio": "../audio/бумага.mp3"},
{"ru": "книга", "gender": "1", "audio": "../audio/книга.mp3"},
{"ru": "тетрадь", "gender": "3", "audio": "../audio/тетрадь.mp3"},
{"ru": "ручка", "gender": "1", "audio": "../audio/ручка.mp3"},
{"ru": "карандаш", "gender": "2", "audio": "../audio/карандаш.mp3"},
{"ru": "линейка", "gender": "1", "audio": "../audio/линейка.mp3"},
{"ru": "степлер", "gender": "2", "audio": "../audio/степлер.mp3"},
{"ru": "игла", "gender": "1", "audio": "../audio/игла.mp3"},
{"ru": "нитка", "gender": "1", "audio": "../audio/нитка.mp3"},
{"ru": "игрушка", "gender": "1", "audio": "../audio/игрушка.mp3"},
{"ru": "животное", "gender": "2", "audio": "../audio/животное.mp3"},
{"ru": "питомец", "gender": "2", "audio": "../audio/питомец.mp3"},
{"ru": "хищник", "gender": "2", "audio": "../audio/хищник.mp3"},
{"ru": "птица", "gender": "1", "audio": "../audio/птица.mp3"},
{"ru": "жук", "gender": "2", "audio": "../audio/жук.mp3"},
{"ru": "рыба", "gender": "1", "audio": "../audio/рыба.mp3"},
{"ru": "кот", "gender": "2", "audio": "../audio/кот.mp3"},
{"ru": "кошка", "gender": "1", "audio": "../audio/кошка.mp3"},
{"ru": "пёс", "gender": "2", "audio": "../audio/пёс.mp3"},
{"ru": "собака", "gender": "1", "audio": "../audio/собака.mp3"},
{"ru": "конь", "gender": "2", "audio": "../audio/конь.mp3"},
{"ru": "лошадь", "gender": "3", "audio": "../audio/лошадь.mp3"},
{"ru": "верблюд", "gender": "2", "audio": "../audio/верблюд.mp3"},
{"ru": "бык", "gender": "2", "audio": "../audio/бык.mp3"},
{"ru": "корова", "gender": "1", "audio": "../audio/корова.mp3"},
{"ru": "телёнок", "gender": "2", "audio": "../audio/телёнок.mp3"},
{"ru": "козёл", "gender": "2", "audio": "../audio/козёл.mp3"},
{"ru": "коза", "gender": "1", "audio": "../audio/коза.mp3"},
{"ru": "козлёнок", "gender": "2", "audio": "../audio/козлёнок.mp3"},
{"ru": "баран", "gender": "2", "audio": "../audio/баран.mp3"},
{"ru": "овца", "gender": "1", "audio": "../audio/овца.mp3"},
{"ru": "ягнёнок", "gender": "2", "audio": "../audio/ягнёнок.mp3"},
{"ru": "осёл", "gender": "2", "audio": "../audio/осёл.mp3"},
{"ru": "кролик", "gender": "2", "audio": "../audio/кролик.mp3"},
{"ru": "заяц", "gender": "2", "audio": "../audio/заяц.mp3"},
{"ru": "кабан", "gender": "2", "audio": "../audio/кабан.mp3"},
{"ru": "свинья", "gender": "1", "audio": "../audio/свинья.mp3"},
{"ru": "петух", "gender": "2", "audio": "../audio/петух.mp3"},
{"ru": "курица", "gender": "1", "audio": "../audio/курица.mp3"},
{"ru": "цыплёнок", "gender": "2", "audio": "../audio/цыплёнок.mp3"},
{"ru": "гусь", "gender": "2", "audio": "../audio/гусь.mp3"},
{"ru": "утка", "gender": "1", "audio": "../audio/утка.mp3"},
{"ru": "павлин", "gender": "2", "audio": "../audio/павлин.mp3"},
{"ru": "лебедь", "gender": "2", "audio": "../audio/лебедь.mp3"},
{"ru": "голубь", "gender": "2", "audio": "../audio/голубь.mp3"},
{"ru": "попугай", "gender": "2", "audio": "../audio/попугай.mp3"},
{"ru": "слон", "gender": "2", "audio": "../audio/слон.mp3"},
{"ru": "бегемот", "gender": "2", "audio": "../audio/бегемот.mp3"},
{"ru": "носорог", "gender": "2", "audio": "../audio/носорог.mp3"},
{"ru": "жираф", "gender": "2", "audio": "../audio/жираф.mp3"},
{"ru": "медведь", "gender": "2", "audio": "../audio/медведь.mp3"},
{"ru": "волк", "gender": "2", "audio": "../audio/волк.mp3"},
{"ru": "лиса", "gender": "1", "audio": "../audio/лиса.mp3"},
{"ru": "лев", "gender": "2", "audio": "../audio/лев.mp3"},
{"ru": "тигр", "gender": "2", "audio": "../audio/тигр.mp3"},
{"ru": "гепард", "gender": "2", "audio": "../audio/гепард.mp3"},
{"ru": "газель", "gender": "1", "audio": "../audio/газель.mp3"},
{"ru": "антилопа", "gender": "1", "audio": "../audio/антилопа.mp3"},
{"ru": "тюлень", "gender": "2", "audio": "../audio/тюлень.mp3"},
{"ru": "енот", "gender": "2", "audio": "../audio/енот.mp3"},
{"ru": "крот", "gender": "2", "audio": "../audio/крот.mp3"},
{"ru": "белка", "gender": "1", "audio": "../audio/белка.mp3"},
{"ru": "хомяк", "gender": "2", "audio": "../audio/хомяк.mp3"},
{"ru": "ёж", "gender": "2", "audio": "../audio/ёж.mp3"},
{"ru": "крыса", "gender": "1", "audio": "../audio/крыса.mp3"},
{"ru": "мышь", "gender": "3", "audio": "../audio/мышь.mp3"},
{"ru": "крокодил", "gender": "2", "audio": "../audio/крокодил.mp3"},
{"ru": "черепаха", "gender": "1", "audio": "../audio/черепаха.mp3"},
{"ru": "пингвин", "gender": "2", "audio": "../audio/пингвин.mp3"},
{"ru": "лягушка", "gender": "1", "audio": "../audio/лягушка.mp3"},
{"ru": "змея", "gender": "1", "audio": "../audio/змея.mp3"},
{"ru": "ящерица", "gender": "1", "audio": "../audio/ящерица.mp3"},
{"ru": "орёл", "gender": "2", "audio": "../audio/орёл.mp3"},
{"ru": "сокол", "gender": "2", "audio": "../audio/сокол.mp3"},
{"ru": "сова", "gender": "1", "audio": "../audio/сова.mp3"},
{"ru": "ворон", "gender": "2", "audio": "../audio/ворон.mp3"},
{"ru": "акула", "gender": "1", "audio": "../audio/акула.mp3"},
{"ru": "дельфин", "gender": "2", "audio": "../audio/дельфин.mp3"},
{"ru": "кит", "gender": "2", "audio": "../audio/кит.mp3"},
{"ru": "краб", "gender": "2", "audio": "../audio/краб.mp3"},
{"ru": "креветка", "gender": "1", "audio": "../audio/креветка.mp3"},
{"ru": "осьминог", "gender": "2", "audio": "../audio/осьминог.mp3"},
{"ru": "скорпион", "gender": "2", "audio": "../audio/скорпион.mp3"},
{"ru": "пчела", "gender": "1", "audio": "../audio/пчела.mp3"},
{"ru": "оса", "gender": "1", "audio": "../audio/оса.mp3"},
{"ru": "комар", "gender": "2", "audio": "../audio/комар.mp3"},
{"ru": "еда", "gender": "1", "audio": "../audio/еда.mp3"},
{"ru": "завтрак", "gender": "2", "audio": "../audio/завтрак.mp3"},
{"ru": "обед", "gender": "2", "audio": "../audio/обед.mp3"},
{"ru": "ужин", "gender": "2", "audio": "../audio/ужин.mp3"},
{"ru": "напиток", "gender": "2", "audio": "../audio/напиток.mp3"},
{"ru": "рыба", "gender": "1", "audio": "../audio/рыба.mp3"},
{"ru": "мясо", "gender": "2", "audio": "../audio/мясо.mp3"},
{"ru": "сыр", "gender": "2", "audio": "../audio/сыр.mp3"},
{"ru": "молоко", "gender": "2", "audio": "../audio/молоко.mp3"},
{"ru": "кефир", "gender": "2", "audio": "../audio/кефир.mp3"},
{"ru": "сметана", "gender": "1", "audio": "../audio/сметана.mp3"},
{"ru": "творог", "gender": "2", "audio": "../audio/творог.mp3"},
{"ru": "йогурт", "gender": "2", "audio": "../audio/йогурт.mp3"},
{"ru": "масло", "gender": "2", "audio": "../audio/масло.mp3"},
{"ru": "мука", "gender": "1", "audio": "../audio/мука.mp3"},
{"ru": "хлеб", "gender": "2", "audio": "../audio/хлеб.mp3"},
{"ru": "вода", "gender": "1", "audio": "../audio/вода.mp3"},
{"ru": "сок", "gender": "2", "audio": "../audio/сок.mp3"},
{"ru": "чай", "gender": "2", "audio": "../audio/чай.mp3"},
{"ru": "кофе", "gender": "2", "audio": "../audio/кофе.mp3"},
{"ru": "говядина", "gender": "1", "audio": "../audio/говядина.mp3"},
{"ru": "телятина", "gender": "1", "audio": "../audio/телятина.mp3"},
{"ru": "баранина", "gender": "1", "audio": "../audio/баранина.mp3"},
{"ru": "свинина", "gender": "1", "audio": "../audio/свинина.mp3"},
{"ru": "крупа", "gender": "1", "audio": "../audio/крупа.mp3"},
{"ru": "рис", "gender": "2", "audio": "../audio/рис.mp3"},
{"ru": "булгур", "gender": "2", "audio": "../audio/булгур.mp3"},
{"ru": "фасоль", "gender": "3", "audio": "../audio/фасоль.mp3"},
{"ru": "горох", "gender": "2", "audio": "../audio/горох.mp3"},
{"ru": "чечевица", "gender": "1", "audio": "../audio/чечевица.mp3"},
{"ru": "пшено", "gender": "2", "audio": "../audio/пшено.mp3"},
{"ru": "суп", "gender": "2", "audio": "../audio/суп.mp3"},
{"ru": "борщ", "gender": "2", "audio": "../audio/борщ.mp3"},
{"ru": "каша", "gender": "1", "audio": "../audio/каша.mp3"},
{"ru": "картофель", "gender": "2", "audio": "../audio/картофель.mp3"},
{"ru": "помидор", "gender": "2", "audio": "../audio/помидор.mp3"},
{"ru": "огурец", "gender": "2", "audio": "../audio/огурец.mp3"},
{"ru": "морковь", "gender": "3", "audio": "../audio/морковь.mp3"},
{"ru": "капуста", "gender": "1", "audio": "../audio/капуста.mp3"},
{"ru": "шпинат", "gender": "2", "audio": "../audio/шпинат.mp3"},
{"ru": "салат", "gender": "2", "audio": "../audio/салат.mp3"},
{"ru": "тыква", "gender": "1", "audio": "../audio/тыква.mp3"},
{"ru": "свёкла", "gender": "1", "audio": "../audio/свёкла.mp3"},
{"ru": "редис", "gender": "2", "audio": "../audio/редис.mp3"},
{"ru": "кабачок", "gender": "2", "audio": "../audio/кабачок.mp3"},
{"ru": "лук", "gender": "2", "audio": "../audio/лук.mp3"},
{"ru": "чеснок", "gender": "2", "audio": "../audio/чеснок.mp3"},
{"ru": "яблоко", "gender": "2", "audio": "../audio/яблоко.mp3"},
{"ru": "груша", "gender": "1", "audio": "../audio/груша.mp3"},
{"ru": "вишня", "gender": "1", "audio": "../audio/вишня.mp3"},
{"ru": "клубника", "gender": "1", "audio": "../audio/клубника.mp3"},
{"ru": "виноград", "gender": "2", "audio": "../audio/виноград.mp3"},
{"ru": "арбуз", "gender": "2", "audio": "../audio/арбуз.mp3"},
{"ru": "банан", "gender": "2", "audio": "../audio/банан.mp3"},
{"ru": "инжир", "gender": "2", "audio": "../audio/инжир.mp3"},
{"ru": "ананас", "gender": "2", "audio": "../audio/ананас.mp3"},
{"ru": "киви", "gender": "2", "audio": "../audio/киви.mp3"},
{"ru": "апельсин", "gender": "2", "audio": "../audio/апельсин.mp3"},
{"ru": "лимон", "gender": "2", "audio": "../audio/лимон.mp3"},
{"ru": "десерт", "gender": "2", "audio": "../audio/десерт.mp3"},
{"ru": "мёд", "gender": "2", "audio": "../audio/мёд.mp3"},
{"ru": "пирог", "gender": "2", "audio": "../audio/пирог.mp3"},
{"ru": "торт", "gender": "2", "audio": "../audio/торт.mp3"},
{"ru": "шоколад", "gender": "2", "audio": "../audio/шоколад.mp3"},
{"ru": "печенье", "gender": "2", "audio": "../audio/печенье.mp3"},
{"ru": "мороженое", "gender": "2", "audio": "../audio/мороженое.mp3"},
{"ru": "соль", "gender": "3", "audio": "../audio/соль.mp3"},
{"ru": "сахар", "gender": "2", "audio": "../audio/сахар.mp3"},
{"ru": "перец", "gender": "2", "audio": "../audio/перец.mp3"},
{"ru": "корица", "gender": "1", "audio": "../audio/корица.mp3"},
{"ru": "куркума", "gender": "1", "audio": "../audio/куркума.mp3"},
{"ru": "мята", "gender": "1", "audio": "../audio/мята.mp3"},
{"ru": "фундук", "gender": "2", "audio": "../audio/фундук.mp3"},
{"ru": "изюм", "gender": "2", "audio": "../audio/изюм.mp3"},
{"ru": "алкоголь", "gender": "2", "audio": "../audio/алкоголь.mp3"},
{"ru": "вино", "gender": "2", "audio": "../audio/вино.mp3"},
{"ru": "пиво", "gender": "2", "audio": "../audio/пиво.mp3"},
{"ru": "учёба", "gender": "1", "audio": "../audio/учёба.mp3"},
{"ru": "учебник", "gender": "2", "audio": "../audio/учебник.mp3"},
{"ru": "словарь", "gender": "2", "audio": "../audio/словарь.mp3"},
{"ru": "профессия", "gender": "1", "audio": "../audio/профессия.mp3"},
{"ru": "специальность", "gender": "3", "audio": "../audio/специальность.mp3"},
{"ru": "школа", "gender": "1", "audio": "../audio/школа.mp3"},
{"ru": "университет", "gender": "2", "audio": "../audio/университет.mp3"},
{"ru": "учитель", "gender": "2", "audio": "../audio/учитель.mp3"},
{"ru": "профессор", "gender": "2", "audio": "../audio/профессор.mp3"},
{"ru": "учёный", "gender": "2", "audio": "../audio/учёный.mp3"},
{"ru": "врач", "gender": "2", "audio": "../audio/врач.mp3"},
{"ru": "инженер", "gender": "2", "audio": "../audio/инженер.mp3"},
{"ru": "адвокат", "gender": "2", "audio": "../audio/адвокат.mp3"},
{"ru": "медсестра", "gender": "1", "audio": "../audio/медсестра.mp3"},
{"ru": "продавец", "gender": "2", "audio": "../audio/продавец.mp3"},
{"ru": "путешествие", "gender": "2", "audio": "../audio/путешествие.mp3"},
{"ru": "путешественник", "gender": "2", "audio": "../audio/путешественник.mp3"},
{"ru": "поездка", "gender": "1", "audio": "../audio/поездка.mp3"},
{"ru": "туризм", "gender": "2", "audio": "../audio/туризм.mp3"},
{"ru": "турист", "gender": "2", "audio": "../audio/турист.mp3"},
{"ru": "экскурсовод", "gender": "2", "audio": "../audio/экскурсовод.mp3"},
{"ru": "экскурсия", "gender": "1", "audio": "../audio/экскурсия.mp3"},
{"ru": "информация", "gender": "1", "audio": "../audio/информация.mp3"},
{"ru": "карта", "gender": "1", "audio": "../audio/карта.mp3"},
{"ru": "кошелёк", "gender": "2", "audio": "../audio/кошелёк.mp3"},
{"ru": "паспорт", "gender": "2", "audio": "../audio/паспорт.mp3"},
{"ru": "виза", "gender": "1", "audio": "../audio/виза.mp3"},
{"ru": "страховка", "gender": "1", "audio": "../audio/страховка.mp3"},
{"ru": "цена", "gender": "1", "audio": "../audio/цена.mp3"},
{"ru": "распродажа", "gender": "1", "audio": "../audio/распродажа.mp3"},
{"ru": "скидка", "gender": "1", "audio": "../audio/скидка.mp3"},
{"ru": "посольство", "gender": "2", "audio": "../audio/посольство.mp3"},
{"ru": "консульство", "gender": "2", "audio": "../audio/консульство.mp3"},
{"ru": "полиция", "gender": "1", "audio": "../audio/полиция.mp3"},
{"ru": "билет", "gender": "2", "audio": "../audio/билет.mp3"},
{"ru": "гостиница", "gender": "1", "audio": "../audio/гостиница.mp3"},
{"ru": "номер", "gender": "2", "audio": "../audio/номер.mp3"},
{"ru": "бронь", "gender": "3", "audio": "../audio/бронь.mp3"},
{"ru": "рейс", "gender": "2", "audio": "../audio/рейс.mp3"},
{"ru": "транзит", "gender": "2", "audio": "../audio/транзит.mp3"},
{"ru": "вход", "gender": "2", "audio": "../audio/вход.mp3"},
{"ru": "выход", "gender": "2", "audio": "../audio/выход.mp3"},
{"ru": "таможня", "gender": "1", "audio": "../audio/таможня.mp3"},
{"ru": "контроль", "gender": "2", "audio": "../audio/контроль.mp3"},
{"ru": "штамп", "gender": "2", "audio": "../audio/штамп.mp3"},
{"ru": "сумка", "gender": "1", "audio": "../audio/сумка.mp3"},
{"ru": "багаж", "gender": "2", "audio": "../audio/багаж.mp3"},
{"ru": "дорога", "gender": "1", "audio": "../audio/дорога.mp3"},
{"ru": "тротуар", "gender": "2", "audio": "../audio/тротуар.mp3"},
{"ru": "транспорт", "gender": "2", "audio": "../audio/транспорт.mp3"},
{"ru": "пассажир", "gender": "2", "audio": "../audio/пассажир.mp3"},
{"ru": "велосипед", "gender": "2", "audio": "../audio/велосипед.mp3"},
{"ru": "машина", "gender": "1", "audio": "../audio/машина.mp3"},
{"ru": "автобус", "gender": "2", "audio": "../audio/автобус.mp3"},
{"ru": "автовокзал", "gender": "2", "audio": "../audio/автовокзал.mp3"},
{"ru": "вертолёт", "gender": "2", "audio": "../audio/вертолёт.mp3"},
{"ru": "самолёт", "gender": "2", "audio": "../audio/самолёт.mp3"},
{"ru": "аэропорт", "gender": "2", "audio": "../audio/аэропорт.mp3"},
{"ru": "поезд", "gender": "2", "audio": "../audio/поезд.mp3"},
{"ru": "метро", "gender": "2", "audio": "../audio/метро.mp3"},
{"ru": "лодка", "gender": "1", "audio": "../audio/лодка.mp3"},
{"ru": "яхта", "gender": "1", "audio": "../audio/яхта.mp3"},
{"ru": "корабль", "gender": "2", "audio": "../audio/корабль.mp3"},
{"ru": "порт", "gender": "2", "audio": "../audio/порт.mp3"},
{"ru": "праздник", "gender": "2", "audio": "../audio/праздник.mp3"},
{"ru": "погода", "gender": "1", "audio": "../audio/погода.mp3"},
{"ru": "небо", "gender": "2", "audio": "../audio/небо.mp3"},
{"ru": "земля", "gender": "1", "audio": "../audio/земля.mp3"},
{"ru": "огонь", "gender": "2", "audio": "../audio/огонь.mp3"},
{"ru": "воздух", "gender": "2", "audio": "../audio/воздух.mp3"},
{"ru": "солнце", "gender": "2", "audio": "../audio/солнце.mp3"},
{"ru": "луна", "gender": "1", "audio": "../audio/луна.mp3"},
{"ru": "звезда", "gender": "1", "audio": "../audio/звезда.mp3"},
{"ru": "дождь", "gender": "2", "audio": "../audio/дождь.mp3"},
{"ru": "ветер", "gender": "2", "audio": "../audio/ветер.mp3"},
{"ru": "град", "gender": "2", "audio": "../audio/град.mp3"},
{"ru": "снег", "gender": "2", "audio": "../audio/снег.mp3"},
{"ru": "море", "gender": "2", "audio": "../audio/море.mp3"},
{"ru": "река", "gender": "1", "audio": "../audio/река.mp3"},
{"ru": "озеро", "gender": "2", "audio": "../audio/озеро.mp3"},
{"ru": "остров", "gender": "2", "audio": "../audio/остров.mp3"},
{"ru": "водопад", "gender": "2", "audio": "../audio/водопад.mp3"},
{"ru": "пещера", "gender": "1", "audio": "../audio/пещера.mp3"},
{"ru": "пляж", "gender": "2", "audio": "../audio/пляж.mp3"},
{"ru": "пустыня", "gender": "1", "audio": "../audio/пустыня.mp3"},
{"ru": "лес", "gender": "2", "audio": "../audio/лес.mp3"},
{"ru": "гора", "gender": "1", "audio": "../audio/гора.mp3"},
{"ru": "вулкан", "gender": "2", "audio": "../audio/вулкан.mp3"},
{"ru": "камень", "gender": "2", "audio": "../audio/камень.mp3"},
{"ru": "авария", "gender": "1", "audio": "../audio/авария.mp3"},
{"ru": "больница", "gender": "1", "audio": "../audio/больница.mp3"},
{"ru": "ресторан", "gender": "2", "audio": "../audio/ресторан.mp3"},
{"ru": "кафе", "gender": "2", "audio": "../audio/кафе.mp3"},
{"ru": "рынок", "gender": "2", "audio": "../audio/рынок.mp3"},
{"ru": "магазин", "gender": "2", "audio": "../audio/магазин.mp3"},
{"ru": "тюрьма", "gender": "1", "audio": "../audio/тюрьма.mp3"},
{"ru": "музей", "gender": "2", "audio": "../audio/музей.mp3"},
{"ru": "стадион", "gender": "2", "audio": "../audio/стадион.mp3"},
{"ru": "концерт", "gender": "2", "audio": "../audio/концерт.mp3"},
{"ru": "сувенир", "gender": "2", "audio": "../audio/сувенир.mp3"},
{"ru": "подарок", "gender": "2", "audio": "../audio/подарок.mp3"},
{"ru": "кальян", "gender": "2", "audio": "../audio/кальян.mp3"},
{"ru": "золото", "gender": "2", "audio": "../audio/золото.mp3"},
{"ru": "серебро", "gender": "2", "audio": "../audio/серебро.mp3"},
{"ru": "платина", "gender": "1", "audio": "../audio/платина.mp3"},
{"ru": "север", "gender": "2", "audio": "../audio/север.mp3"},
{"ru": "юг", "gender": "2", "audio": "../audio/юг.mp3"},
{"ru": "запад", "gender": "2", "audio": "../audio/запад.mp3"},
{"ru": "восток", "gender": "2", "audio": "../audio/восток.mp3"},
{"ru": "страна", "gender": "1", "audio": "../audio/страна.mp3"},
{"ru": "город", "gender": "2", "audio": "../audio/город.mp3"},
{"ru": "столица", "gender": "1", "audio": "../audio/столица.mp3"},
{"ru": "деревня", "gender": "1", "audio": "../audio/деревня.mp3"},
{"ru": "Россия", "gender": "1", "audio": "../audio/Россия.mp3"},
{"ru": "Москва", "gender": "1", "audio": "../audio/Москва.mp3"},
{"ru": "Санкт‑Петербург", "gender": "2", "audio": "../audio/Санкт-Петербург.mp3"},
{"ru": "Иордания", "gender": "1", "audio": "../audio/Иордания.mp3"},
{"ru": "Ирак", "gender": "2", "audio": "../audio/Ирак.mp3"},
{"ru": "Багдад", "gender": "2", "audio": "../audio/Багдад.mp3"},
{"ru": "Сирия", "gender": "1", "audio": "../audio/Сирия.mp3"},
{"ru": "Дамаск", "gender": "2", "audio": "../audio/Дамаск.mp3"}



    ];

    const genders = [
        { id: "1", label: "التصريف الأول للأسماء" },
        { id: "2", label: "التصريف الثاني للأسماء" },
        { id: "3", label: "التصريف الثالث للأسماء" }
    ];

    let correctWord = null;
    let hasAnswered = false;

    let correctCount = 0;
    let wrongCount = 0;

    const wordButton = document.getElementById("word-button");
    const optionsContainer = document.getElementById("options");
    const resultBox = document.getElementById("result");
    const scoreBox = document.getElementById("score");

    const nextButton = document.createElement("button");
    nextButton.textContent = "🌿 التالي";
    nextButton.style.display = "none";
    nextButton.className = "next-button";
    nextButton.onclick = () => {
        renderQuestion();
        nextButton.style.display = "none";
        hasAnswered = false;
    };
    document.getElementById("next-button-container").appendChild(nextButton);

    function updateScore() {
        scoreBox.textContent = `✅: ${correctCount} | ❌: ${wrongCount}`;
    }

    function getRandomWord() {
        return words[Math.floor(Math.random() * words.length)];
    }

    function renderQuestion() {
        correctWord = getRandomWord();
        resultBox.textContent = "";
        optionsContainer.innerHTML = "";

        wordButton.textContent = correctWord.ru;
        wordButton.onclick = () => {
            new Audio(correctWord.audio).play();
        };

        genders.forEach(g => {
            const btn = document.createElement("button");
            btn.textContent = g.label;
            btn.lang = "ar";
            btn.onclick = () => checkAnswer(g.id);
            optionsContainer.appendChild(btn);
        });
    }

    function checkAnswer(selectedGender) {
        if (hasAnswered) return;
        hasAnswered = true;
    
        document
            .querySelectorAll("#options button")
            .forEach(b => b.disabled = true);
    
        const correctLabel = genders.find(g => g.id === correctWord.gender).label;
    
        if (selectedGender === correctWord.gender) {
            resultBox.textContent = "✅ صح";
            resultBox.style.color = "green";
            correctCount++;
        } else {
            resultBox.innerHTML =
                `<span dir="rtl" lang="ar">❌ خطأ. الإجابة الصحيحة: ${correctLabel}</span>`;
            resultBox.style.color = "red";
            wrongCount++;
        }
    
        updateScore();
        nextButton.style.display = "inline-block";
    }
    

    renderQuestion();
    updateScore();
};
