window.onload = function () {

    const words = [
        { ru: "время", gender: "n", audio: "../audio/время.mp3" },
        { ru: "день", gender: "m", audio: "../audio/день.mp3" },
        { ru: "неделя", gender: "f", audio: "../audio/неделя.mp3" },
        { ru: "минута", gender: "f", audio: "../audio/минута.mp3" },
        { ru: "окно", gender: "n", audio: "../audio/окно.mp3" },
        { ru: "год", gender: "m", audio: "../audio/год.mp3" },


        { "ru": "буква", "gender": "f", "audio": "../audio/буква.mp3" },
        { "ru": "язык", "gender": "m", "audio": "../audio/язык.mp3" },
        { "ru": "звук", "gender": "m", "audio": "../audio/звук.mp3" },
     
        { "ru": "человек", "gender": "m", "audio": "../audio/человек.mp3" },
        { "ru": "мужчина", "gender": "m", "audio": "../audio/мужчина.mp3" },
        { "ru": "женщина", "gender": "f", "audio": "../audio/женщина.mp3" },
        { "ru": "жизнь", "gender": "f", "audio": "../audio/жизнь.mp3" },
        { "ru": "смерть", "gender": "f", "audio": "../audio/смерть.mp3" },
        { "ru": "папа", "gender": "m", "audio": "../audio/папа.mp3" },
        { "ru": "мама", "gender": "f", "audio": "../audio/мама.mp3" },
        { "ru": "отец", "gender": "m", "audio": "../audio/отец.mp3" },
        { "ru": "мать", "gender": "f", "audio": "../audio/мать.mp3" },
        { "ru": "ребёнок", "gender": "m", "audio": "../audio/ребёнок.mp3" },
        { "ru": "младенец", "gender": "m", "audio": "../audio/младенец.mp3" },
        { "ru": "потомство", "gender": "n", "audio": "../audio/потомство.mp3" },
        { "ru": "сын", "gender": "m", "audio": "../audio/сын.mp3" },
        { "ru": "дочь", "gender": "f", "audio": "../audio/дочь.mp3" },
        { "ru": "пасынок", "gender": "m", "audio": "../audio/пасынок.mp3" },
        { "ru": "падчерица", "gender": "f", "audio": "../audio/падчерица.mp3" },
        { "ru": "брат", "gender": "m", "audio": "../audio/брат.mp3" },
        { "ru": "близнец", "gender": "m", "audio": "../audio/близнец.mp3" },
        { "ru": "сестра", "gender": "f", "audio": "../audio/сестра.mp3" },
        { "ru": "дедушка", "gender": "m", "audio": "../audio/дедушка.mp3" },
        { "ru": "бабушка", "gender": "f", "audio": "../audio/бабушка.mp3" },
        { "ru": "внук", "gender": "m", "audio": "../audio/внук.mp3" },
        { "ru": "внучка", "gender": "f", "audio": "../audio/внучка.mp3" },
        { "ru": "дядя", "gender": "m", "audio": "../audio/дядя.mp3" },
        { "ru": "тётя", "gender": "f", "audio": "../audio/тётя.mp3" },
        { "ru": "отчим", "gender": "m", "audio": "../audio/отчим.mp3" },
        { "ru": "мачеха", "gender": "f", "audio": "../audio/мачеха.mp3" },
        { "ru": "родственник", "gender": "m", "audio": "../audio/родственник.mp3" },
        { "ru": "родственница", "gender": "f", "audio": "../audio/родственница.mp3" },
        { "ru": "семья", "gender": "f", "audio": "../audio/семья.mp3" },
        { "ru": "имя", "gender": "n", "audio": "../audio/имя.mp3" },
        { "ru": "отчество", "gender": "n", "audio": "../audio/отчество.mp3" },
        { "ru": "фамилия", "gender": "f", "audio": "../audio/фамилия.mp3" },
        { "ru": "помолвка", "gender": "f", "audio": "../audio/помолвка.mp3" },
        { "ru": "свадьба", "gender": "f", "audio": "../audio/свадьба.mp3" },
        { "ru": "жених", "gender": "m", "audio": "../audio/жених.mp3" },
        { "ru": "невеста", "gender": "f", "audio": "../audio/невеста.mp3" },
        { "ru": "брак", "gender": "m", "audio": "../audio/брак.mp3" },
        { "ru": "муж", "gender": "m", "audio": "../audio/муж.mp3" },
        { "ru": "жена", "gender": "f", "audio": "../audio/жена.mp3" },
        { "ru": "зять", "gender": "m", "audio": "../audio/зять.mp3" },
        { "ru": "невестка", "gender": "f", "audio": "../audio/невестка.mp3" },
        { "ru": "свёкор", "gender": "m", "audio": "../audio/свёкор.mp3" },
        { "ru": "тесть", "gender": "m", "audio": "../audio/тесть.mp3" },
        { "ru": "свекровь", "gender": "f", "audio": "../audio/свекровь.mp3" },
        { "ru": "тёща", "gender": "f", "audio": "../audio/тёща.mp3" },
        { "ru": "деверь", "gender": "m", "audio": "../audio/деверь.mp3" },
        { "ru": "развод", "gender": "m", "audio": "../audio/развод.mp3" },
        { "ru": "кладбище", "gender": "n", "audio": "../audio/кладбище.mp3" },
        { "ru": "могила", "gender": "f", "audio": "../audio/могила.mp3" },
        { "ru": "гроб", "gender": "m", "audio": "../audio/гроб.mp3" },
        { "ru": "вдовец", "gender": "m", "audio": "../audio/вдовец.mp3" },
        { "ru": "вдова", "gender": "f", "audio": "../audio/вдова.mp3" },




        { "ru": "тело", "gender": "n", "audio": "../audio/тело.mp3" },
  { "ru": "голова", "gender": "f", "audio": "../audio/голова.mp3" },
  { "ru": "лицо", "gender": "n", "audio": "../audio/лицо.mp3" },
  { "ru": "лоб", "gender": "m", "audio": "../audio/лоб.mp3" },
  { "ru": "бровь", "gender": "f", "audio": "../audio/бровь.mp3" },
  { "ru": "веко", "gender": "n", "audio": "../audio/веко.mp3" },
  { "ru": "глаз", "gender": "m", "audio": "../audio/глаз.mp3" },
  { "ru": "зрачок", "gender": "m", "audio": "../audio/зрачок.mp3" },
  { "ru": "щека", "gender": "f", "audio": "../audio/щека.mp3" },
  { "ru": "нос", "gender": "m", "audio": "../audio/нос.mp3" },
  { "ru": "ухо", "gender": "n", "audio": "../audio/ухо.mp3" },
  { "ru": "рот", "gender": "m", "audio": "../audio/рот.mp3" },
  { "ru": "губа", "gender": "f", "audio": "../audio/губа.mp3" },
  { "ru": "язык", "gender": "m", "audio": "../audio/язык.mp3" },
  { "ru": "десна", "gender": "f", "audio": "../audio/десна.mp3" },
  { "ru": "зуб", "gender": "m", "audio": "../audio/зуб.mp3" },
  { "ru": "борода", "gender": "f", "audio": "../audio/борода.mp3" },
  { "ru": "шея", "gender": "f", "audio": "../audio/шея.mp3" },
  { "ru": "горло", "gender": "n", "audio": "../audio/горло.mp3" },
  { "ru": "голос", "gender": "m", "audio": "../audio/голос.mp3" },
  { "ru": "плечо", "gender": "n", "audio": "../audio/плечо.mp3" },
  { "ru": "рука", "gender": "f", "audio": "../audio/рука.mp3" },
  { "ru": "локоть", "gender": "m", "audio": "../audio/локоть.mp3" },
  { "ru": "запястье", "gender": "n", "audio": "../audio/запястье.mp3" },
  { "ru": "ладонь", "gender": "f", "audio": "../audio/ладонь.mp3" },
  { "ru": "кулак", "gender": "m", "audio": "../audio/кулак.mp3" },
  { "ru": "палец", "gender": "m", "audio": "../audio/палец.mp3" },
  { "ru": "ноготь", "gender": "m", "audio": "../audio/ноготь.mp3" },
  { "ru": "грудь", "gender": "f", "audio": "../audio/грудь.mp3" },
  { "ru": "спина", "gender": "f", "audio": "../audio/спина.mp3" },
  { "ru": "бедро", "gender": "n", "audio": "../audio/бедро.mp3" },
  { "ru": "нога", "gender": "f", "audio": "../audio/нога.mp3" },
  { "ru": "колено", "gender": "n", "audio": "../audio/колено.mp3" },
  { "ru": "лодыжка", "gender": "f", "audio": "../audio/лодыжка.mp3" },
  { "ru": "пятка", "gender": "f", "audio": "../audio/пятка.mp3" },
  { "ru": "кость", "gender": "f", "audio": "../audio/кость.mp3" },
  { "ru": "ребро", "gender": "n", "audio": "../audio/ребро.mp3" },
  { "ru": "сердце", "gender": "n", "audio": "../audio/сердце.mp3" },
  { "ru": "печень", "gender": "f", "audio": "../audio/печень.mp3" },
  { "ru": "желудок", "gender": "m", "audio": "../audio/желудок.mp3" },
  { "ru": "кровь", "gender": "f", "audio": "../audio/кровь.mp3" },
  { "ru": "здоровье", "gender": "n", "audio": "../audio/здоровье.mp3" },
  { "ru": "болезнь", "gender": "f", "audio": "../audio/болезнь.mp3" },
  { "ru": "кашель", "gender": "m", "audio": "../audio/кашель.mp3" },
  { "ru": "насморк", "gender": "m", "audio": "../audio/насморк.mp3" },
  { "ru": "температура", "gender": "f", "audio": "../audio/температура.mp3" },
  { "ru": "давление", "gender": "n", "audio": "../audio/давление.mp3" },
  { "ru": "боль", "gender": "f", "audio": "../audio/боль.mp3" },
  { "ru": "рана", "gender": "f", "audio": "../audio/рана.mp3" },
  { "ru": "перелом", "gender": "m", "audio": "../audio/перелом.mp3" },
  { "ru": "лекарство", "gender": "n", "audio": "../audio/лекарство.mp3" },


        { "ru": "одежда", "gender": "f", "audio": "../audio/одежда.mp3" },
        { "ru": "шапка", "gender": "f", "audio": "../audio/шапка.mp3" },
        { "ru": "рубашка", "gender": "f", "audio": "../audio/рубашка.mp3" },
        { "ru": "пиджак", "gender": "m", "audio": "../audio/пиджак.mp3" },
        { "ru": "костюм", "gender": "m", "audio": "../audio/костюм.mp3" },
        { "ru": "форма", "gender": "f", "audio": "../audio/форма.mp3" },
        { "ru": "халат", "gender": "m", "audio": "../audio/халат.mp3" },
        { "ru": "платье", "gender": "n", "audio": "../audio/платье.mp3" },
        { "ru": "ремень", "gender": "m", "audio": "../audio/ремень.mp3" },
        { "ru": "шуба", "gender": "f", "audio": "../audio/шуба.mp3" },
        { "ru": "обувь", "gender": "f", "audio": "../audio/обувь.mp3" },
        { "ru": "пуговица", "gender": "f", "audio": "../audio/пуговица.mp3" },
        { "ru": "карман", "gender": "m", "audio": "../audio/карман.mp3" },
        { "ru": "ткань", "gender": "f", "audio": "../audio/ткань.mp3" },
        { "ru": "шёлк", "gender": "m", "audio": "../audio/шёлк.mp3" },
        { "ru": "хлопок", "gender": "m", "audio": "../audio/хлопок.mp3" },
        { "ru": "лён", "gender": "m", "audio": "../audio/лён.mp3" },
        { "ru": "шерсть", "gender": "f", "audio": "../audio/шерсть.mp3" },

        { "ru": "дом", "gender": "m", "audio": "../audio/дом.mp3" },
        { "ru": "жильё", "gender": "n", "audio": "../audio/жильё.mp3" },
        { "ru": "дворец", "gender": "m", "audio": "../audio/дворец.mp3" },
        { "ru": "шатёр", "gender": "m", "audio": "../audio/шатёр.mp3" },
        { "ru": "квартира", "gender": "f", "audio": "../audio/квартира.mp3" },
        { "ru": "стена", "gender": "f", "audio": "../audio/стена.mp3" },
        { "ru": "дверь", "gender": "f", "audio": "../audio/дверь.mp3" },
        { "ru": "окно", "gender": "n", "audio": "../audio/окно.mp3" },
        { "ru": "пол", "gender": "m", "audio": "../audio/пол.mp3" },
        { "ru": "потолок", "gender": "m", "audio": "../audio/потолок.mp3" },
        { "ru": "крыша", "gender": "f", "audio": "../audio/крыша.mp3" },
        { "ru": "подвал", "gender": "m", "audio": "../audio/подвал.mp3" },
        { "ru": "этаж", "gender": "m", "audio": "../audio/этаж.mp3" },
        { "ru": "лестница", "gender": "f", "audio": "../audio/лестница.mp3" },
        { "ru": "замок", "gender": "m", "audio": "../audio/замок.mp3" },
        { "ru": "ключ", "gender": "m", "audio": "../audio/ключ.mp3" },
        { "ru": "гараж", "gender": "m", "audio": "../audio/гараж.mp3" },
        { "ru": "комната", "gender": "f", "audio": "../audio/комната.mp3" },
        { "ru": "кухня", "gender": "f", "audio": "../audio/кухня.mp3" },
        { "ru": "спальня", "gender": "f", "audio": "../audio/спальня.mp3" },
        { "ru": "библиотека", "gender": "f", "audio": "../audio/библиотека.mp3" },
        { "ru": "склад", "gender": "m", "audio": "../audio/склад.mp3" },
        { "ru": "туалет", "gender": "m", "audio": "../audio/туалет.mp3" },
        { "ru": "мебель", "gender": "f", "audio": "../audio/мебель.mp3" },
        { "ru": "стол", "gender": "m", "audio": "../audio/стол.mp3" },
        { "ru": "стул", "gender": "m", "audio": "../audio/стул.mp3" },
        { "ru": "шкаф", "gender": "m", "audio": "../audio/шкаф.mp3" },
        { "ru": "гардероб", "gender": "m", "audio": "../audio/гардероб.mp3" },
        { "ru": "полка", "gender": "f", "audio": "../audio/полка.mp3" },
        { "ru": "кровать", "gender": "f", "audio": "../audio/кровать.mp3" },
        { "ru": "диван", "gender": "m", "audio": "../audio/диван.mp3" },
        { "ru": "кресло", "gender": "n", "audio": "../audio/кресло.mp3" },
        { "ru": "вешалка", "gender": "f", "audio": "../audio/вешалка.mp3" },
        { "ru": "лампа", "gender": "f", "audio": "../audio/лампа.mp3" },
        { "ru": "зеркало", "gender": "n", "audio": "../audio/зеркало.mp3" },
        { "ru": "расчёска", "gender": "f", "audio": "../audio/расчёска.mp3" },
        { "ru": "бритва", "gender": "f", "audio": "../audio/бритва.mp3" },
        { "ru": "мыло", "gender": "n", "audio": "../audio/мыло.mp3" },
        { "ru": "шампунь", "gender": "m", "audio": "../audio/шампунь.mp3" },
        { "ru": "одеяло", "gender": "n", "audio": "../audio/одеяло.mp3" },
        { "ru": "простыня", "gender": "f", "audio": "../audio/простыня.mp3" },
        { "ru": "подушка", "gender": "f", "audio": "../audio/подушка.mp3" },
        { "ru": "полотенце", "gender": "n", "audio": "../audio/полотенце.mp3" },
        { "ru": "занавеска", "gender": "f", "audio": "../audio/занавеска.mp3" },
        { "ru": "ковёр", "gender": "m", "audio": "../audio/ковёр.mp3" },
        { "ru": "зонт", "gender": "m", "audio": "../audio/зонт.mp3" },
        { "ru": "чайник", "gender": "m", "audio": "../audio/чайник.mp3" },
        { "ru": "кастрюля", "gender": "f", "audio": "../audio/кастрюля.mp3" },
        { "ru": "сковорода", "gender": "f", "audio": "../audio/сковорода.mp3" },
        { "ru": "миска", "gender": "f", "audio": "../audio/миска.mp3" },
        { "ru": "половник", "gender": "m", "audio": "../audio/половник.mp3" },
        { "ru": "тарелка", "gender": "f", "audio": "../audio/тарелка.mp3" },
        { "ru": "ложка", "gender": "f", "audio": "../audio/ложка.mp3" },
        { "ru": "вилка", "gender": "f", "audio": "../audio/вилка.mp3" },
        { "ru": "нож", "gender": "m", "audio": "../audio/нож.mp3" },
        { "ru": "душ", "gender": "m", "audio": "../audio/душ.mp3" },
        { "ru": "ванна", "gender": "f", "audio": "../audio/ванна.mp3" },
        { "ru": "бассейн", "gender": "m", "audio": "../audio/бассейн.mp3" },
        { "ru": "раковина", "gender": "f", "audio": "../audio/раковина.mp3" },
        { "ru": "кран", "gender": "m", "audio": "../audio/кран.mp3" },
        { "ru": "холодильник", "gender": "m", "audio": "../audio/холодильник.mp3" },
        { "ru": "пылесос", "gender": "m", "audio": "../audio/пылесос.mp3" },
        { "ru": "утюг", "gender": "m", "audio": "../audio/утюг.mp3" },
        { "ru": "вентилятор", "gender": "m", "audio": "../audio/вентилятор.mp3" },
        { "ru": "кондиционер", "gender": "m", "audio": "../audio/кондиционер.mp3" },
        { "ru": "плита", "gender": "f", "audio": "../audio/плита.mp3" },
        { "ru": "микроволновка", "gender": "f", "audio": "../audio/микроволновка.mp3" },
        { "ru": "тостер", "gender": "m", "audio": "../audio/тостер.mp3" },
        { "ru": "телевизор", "gender": "m", "audio": "../audio/телевизор.mp3" },
        { "ru": "телефон", "gender": "m", "audio": "../audio/телефон.mp3" },
        { "ru": "радио", "gender": "n", "audio": "../audio/радио.mp3" },
        { "ru": "сад", "gender": "m", "audio": "../audio/сад.mp3" },
        { "ru": "цветок", "gender": "m", "audio": "../audio/цветок.mp3" },
        { "ru": "дерево", "gender": "n", "audio": "../audio/дерево.mp3" },
        { "ru": "трава", "gender": "f", "audio": "../audio/трава.mp3" },
        { "ru": "ремонт", "gender": "m", "audio": "../audio/ремонт.mp3" },
        { "ru": "уборка", "gender": "f", "audio": "../audio/уборка.mp3" },
        { "ru": "стирка", "gender": "f", "audio": "../audio/стирка.mp3" },
        { "ru": "мусор", "gender": "m", "audio": "../audio/мусор.mp3" },
        { "ru": "салфетка", "gender": "f", "audio": "../audio/салфетка.mp3" },
        { "ru": "тряпка", "gender": "f", "audio": "../audio/тряпка.mp3" },
        { "ru": "ведро", "gender": "n", "audio": "../audio/ведро.mp3" },
        { "ru": "таз", "gender": "m", "audio": "../audio/таз.mp3" },
        { "ru": "веник", "gender": "m", "audio": "../audio/веник.mp3" },
        { "ru": "совок", "gender": "m", "audio": "../audio/совок.mp3" },
        { "ru": "швабра", "gender": "f", "audio": "../audio/швабра.mp3" },
        { "ru": "порошок", "gender": "m", "audio": "../audio/порошок.mp3" },
        { "ru": "пила", "gender": "f", "audio": "../audio/пила.mp3" },
        { "ru": "молоток", "gender": "m", "audio": "../audio/молоток.mp3" },
        { "ru": "отвёртка", "gender": "f", "audio": "../audio/отвёртка.mp3" },
        { "ru": "документ", "gender": "m", "audio": "../audio/документ.mp3" },
        { "ru": "бумага", "gender": "f", "audio": "../audio/бумага.mp3" },
        { "ru": "книга", "gender": "f", "audio": "../audio/книга.mp3" },
        { "ru": "тетрадь", "gender": "f", "audio": "../audio/тетрадь.mp3" },
        { "ru": "ручка", "gender": "f", "audio": "../audio/ручка.mp3" },
        { "ru": "карандаш", "gender": "m", "audio": "../audio/карандаш.mp3" },
        { "ru": "линейка", "gender": "f", "audio": "../audio/линейка.mp3" },
        { "ru": "степлер", "gender": "m", "audio": "../audio/степлер.mp3" },
        { "ru": "игла", "gender": "f", "audio": "../audio/игла.mp3" },
        { "ru": "нитка", "gender": "f", "audio": "../audio/нитка.mp3" },
        { "ru": "игрушка", "gender": "f", "audio": "../audio/игрушка.mp3" },


        { "ru": "животное", "gender": "n", "audio": "../audio/животное.mp3" },
        { "ru": "питомец", "gender": "m", "audio": "../audio/питомец.mp3" },
        { "ru": "хищник", "gender": "m", "audio": "../audio/хищник.mp3" },
        { "ru": "птица", "gender": "f", "audio": "../audio/птица.mp3" },
        { "ru": "жук", "gender": "m", "audio": "../audio/жук.mp3" },
        { "ru": "рыба", "gender": "f", "audio": "../audio/рыба.mp3" },
        { "ru": "кот", "gender": "m", "audio": "../audio/кот.mp3" },
        { "ru": "кошка", "gender": "f", "audio": "../audio/кошка.mp3" },
        { "ru": "пёс", "gender": "m", "audio": "../audio/пёс.mp3" },
        { "ru": "собака", "gender": "f", "audio": "../audio/собака.mp3" },
        { "ru": "конь", "gender": "m", "audio": "../audio/конь.mp3" },
        { "ru": "лошадь", "gender": "f", "audio": "../audio/лошадь.mp3" },
        { "ru": "верблюд", "gender": "m", "audio": "../audio/верблюд.mp3" },
        { "ru": "бык", "gender": "m", "audio": "../audio/бык.mp3" },
        { "ru": "корова", "gender": "f", "audio": "../audio/корова.mp3" },
        { "ru": "телёнок", "gender": "m", "audio": "../audio/телёнок.mp3" },
        { "ru": "козёл", "gender": "m", "audio": "../audio/козёл.mp3" },
        { "ru": "коза", "gender": "f", "audio": "../audio/коза.mp3" },
        { "ru": "козлёнок", "gender": "m", "audio": "../audio/козлёнок.mp3" },
        { "ru": "баран", "gender": "m", "audio": "../audio/баран.mp3" },
        { "ru": "овца", "gender": "f", "audio": "../audio/овца.mp3" },
        { "ru": "ягнёнок", "gender": "m", "audio": "../audio/ягнёнок.mp3" },
        { "ru": "осёл", "gender": "m", "audio": "../audio/осёл.mp3" },
        { "ru": "кролик", "gender": "m", "audio": "../audio/кролик.mp3" },
        { "ru": "заяц", "gender": "m", "audio": "../audio/заяц.mp3" },
        { "ru": "кабан", "gender": "m", "audio": "../audio/кабан.mp3" },
        { "ru": "свинья", "gender": "f", "audio": "../audio/свинья.mp3" },
        { "ru": "петух", "gender": "m", "audio": "../audio/петух.mp3" },
        { "ru": "курица", "gender": "f", "audio": "../audio/курица.mp3" },
        { "ru": "цыплёнок", "gender": "m", "audio": "../audio/цыплёнок.mp3" },
        { "ru": "гусь", "gender": "m", "audio": "../audio/гусь.mp3" },
        { "ru": "утка", "gender": "f", "audio": "../audio/утка.mp3" },
        { "ru": "павлин", "gender": "m", "audio": "../audio/павлин.mp3" },
        { "ru": "лебедь", "gender": "m", "audio": "../audio/лебедь.mp3" },
        { "ru": "голубь", "gender": "m", "audio": "../audio/голубь.mp3" },
        { "ru": "попугай", "gender": "m", "audio": "../audio/попугай.mp3" },
        { "ru": "слон", "gender": "m", "audio": "../audio/слон.mp3" },
        { "ru": "бегемот", "gender": "m", "audio": "../audio/бегемот.mp3" },
        { "ru": "носорог", "gender": "m", "audio": "../audio/носорог.mp3" },
        { "ru": "жираф", "gender": "m", "audio": "../audio/жираф.mp3" },
        { "ru": "медведь", "gender": "m", "audio": "../audio/медведь.mp3" },
        { "ru": "волк", "gender": "m", "audio": "../audio/волк.mp3" },
        { "ru": "лиса", "gender": "f", "audio": "../audio/лиса.mp3" },
        { "ru": "лев", "gender": "m", "audio": "../audio/лев.mp3" },
        { "ru": "тигр", "gender": "m", "audio": "../audio/тигр.mp3" },
        { "ru": "гепард", "gender": "m", "audio": "../audio/гепард.mp3" },
        { "ru": "газель", "gender": "f", "audio": "../audio/газель.mp3" },
        { "ru": "антилопа", "gender": "f", "audio": "../audio/антилопа.mp3" },
        { "ru": "тюлень", "gender": "m", "audio": "../audio/тюлень.mp3" },
        { "ru": "енот", "gender": "m", "audio": "../audio/енот.mp3" },
        { "ru": "крот", "gender": "m", "audio": "../audio/крот.mp3" },
        { "ru": "белка", "gender": "f", "audio": "../audio/белка.mp3" },
        { "ru": "хомяк", "gender": "m", "audio": "../audio/хомяк.mp3" },
        { "ru": "ёж", "gender": "m", "audio": "../audio/ёж.mp3" },
        { "ru": "крыса", "gender": "f", "audio": "../audio/крыса.mp3" },
        { "ru": "мышь", "gender": "f", "audio": "../audio/мышь.mp3" },
        { "ru": "крокодил", "gender": "m", "audio": "../audio/крокодил.mp3" },
        { "ru": "черепаха", "gender": "f", "audio": "../audio/черепаха.mp3" },
        { "ru": "пингвин", "gender": "m", "audio": "../audio/пингвин.mp3" },
        { "ru": "лягушка", "gender": "f", "audio": "../audio/лягушка.mp3" },
        { "ru": "змея", "gender": "f", "audio": "../audio/змея.mp3" },
        { "ru": "ящерица", "gender": "f", "audio": "../audio/ящерица.mp3" },
        { "ru": "орёл", "gender": "m", "audio": "../audio/орёл.mp3" },
        { "ru": "сокол", "gender": "m", "audio": "../audio/сокол.mp3" },
        { "ru": "сова", "gender": "f", "audio": "../audio/сова.mp3" },
        { "ru": "ворон", "gender": "m", "audio": "../audio/ворон.mp3" },
        { "ru": "акула", "gender": "f", "audio": "../audio/акула.mp3" },
        { "ru": "дельфин", "gender": "m", "audio": "../audio/дельфин.mp3" },
        { "ru": "кит", "gender": "m", "audio": "../audio/кит.mp3" },
        { "ru": "краб", "gender": "m", "audio": "../audio/краб.mp3" },
        { "ru": "креветка", "gender": "f", "audio": "../audio/креветка.mp3" },
        { "ru": "осьминог", "gender": "m", "audio": "../audio/осьминог.mp3" },
        { "ru": "скорпион", "gender": "m", "audio": "../audio/скорпион.mp3" },
        { "ru": "пчела", "gender": "f", "audio": "../audio/пчела.mp3" },
        { "ru": "оса", "gender": "f", "audio": "../audio/оса.mp3" },
        { "ru": "комар", "gender": "m", "audio": "../audio/комар.mp3" },
        { "ru": "муха", "gender": "f", "audio": "../audio/муха.mp3" },
        { "ru": "бабочка", "gender": "f", "audio": "../audio/бабочка.mp3" },
        { "ru": "муравей", "gender": "m", "audio": "../audio/муравей.mp3" },
        { "ru": "паук", "gender": "m", "audio": "../audio/паук.mp3" },
        { "ru": "саранча", "gender": "f", "audio": "../audio/саранча.mp3" },
        { "ru": "кузнечик", "gender": "m", "audio": "../audio/кузнечик.mp3" },
        { "ru": "таракан", "gender": "m", "audio": "../audio/таракан.mp3" },
        { "ru": "светлячок", "gender": "m", "audio": "../audio/светлячок.mp3" },
        { "ru": "лапа", "gender": "f", "audio": "../audio/лапа.mp3" },
        { "ru": "хвост", "gender": "m", "audio": "../audio/хвост.mp3" },
        { "ru": "клюв", "gender": "m", "audio": "../audio/клюв.mp3" },
        { "ru": "перо", "gender": "n", "audio": "../audio/перо.mp3" },
        { "ru": "крыло", "gender": "n", "audio": "../audio/крыло.mp3" },
        { "ru": "сарай", "gender": "m", "audio": "../audio/сарай.mp3" },
        { "ru": "клетка", "gender": "f", "audio": "../audio/клетка.mp3" },
        { "ru": "аквариум", "gender": "m", "audio": "../audio/аквариум.mp3" },
        { "ru": "корм", "gender": "m", "audio": "../audio/корм.mp3" },
        { "ru": "прививка", "gender": "f", "audio": "../audio/прививка.mp3" },
        { "ru": "зоопарк", "gender": "m", "audio": "../audio/зоопарк.mp3" },


        { "ru": "еда", "gender": "f", "audio": "../audio/еда.mp3" },
        { "ru": "завтрак", "gender": "m", "audio": "../audio/завтрак.mp3" },
        { "ru": "обед", "gender": "m", "audio": "../audio/обед.mp3" },
        { "ru": "ужин", "gender": "m", "audio": "../audio/ужин.mp3" },
        { "ru": "напиток", "gender": "m", "audio": "../audio/напиток.mp3" },
        { "ru": "рыба", "gender": "f", "audio": "../audio/рыба.mp3" },
        { "ru": "мясо", "gender": "n", "audio": "../audio/мясо.mp3" },
        { "ru": "сыр", "gender": "m", "audio": "../audio/сыр.mp3" },
        { "ru": "молоко", "gender": "n", "audio": "../audio/молоко.mp3" },
        { "ru": "кефир", "gender": "m", "audio": "../audio/кефир.mp3" },
        { "ru": "сметана", "gender": "f", "audio": "../audio/сметана.mp3" },
        { "ru": "творог", "gender": "m", "audio": "../audio/творог.mp3" },
        { "ru": "йогурт", "gender": "m", "audio": "../audio/йогурт.mp3" },
        { "ru": "масло", "gender": "n", "audio": "../audio/масло.mp3" },
        { "ru": "мука", "gender": "f", "audio": "../audio/мука.mp3" },
        { "ru": "хлеб", "gender": "m", "audio": "../audio/хлеб.mp3" },
        { "ru": "вода", "gender": "f", "audio": "../audio/вода.mp3" },
        { "ru": "сок", "gender": "m", "audio": "../audio/сок.mp3" },
        { "ru": "чай", "gender": "m", "audio": "../audio/чай.mp3" },
        { "ru": "кофе", "gender": "m", "audio": "../audio/кофе.mp3" },
        { "ru": "говядина", "gender": "f", "audio": "../audio/говядина.mp3" },
        { "ru": "телятина", "gender": "f", "audio": "../audio/телятина.mp3" },
        { "ru": "баранина", "gender": "f", "audio": "../audio/баранина.mp3" },
        { "ru": "свинина", "gender": "f", "audio": "../audio/свинина.mp3" },
        { "ru": "крупа", "gender": "f", "audio": "../audio/крупа.mp3" },
        { "ru": "рис", "gender": "m", "audio": "../audio/рис.mp3" },
        { "ru": "булгур", "gender": "m", "audio": "../audio/булгур.mp3" },
        { "ru": "фасоль", "gender": "f", "audio": "../audio/фасоль.mp3" },
        { "ru": "горох", "gender": "m", "audio": "../audio/горох.mp3" },
        { "ru": "чечевица", "gender": "f", "audio": "../audio/чечевица.mp3" },
        { "ru": "пшено", "gender": "n", "audio": "../audio/пшено.mp3" },
        { "ru": "суп", "gender": "m", "audio": "../audio/суп.mp3" },
        { "ru": "борщ", "gender": "m", "audio": "../audio/борщ.mp3" },
        { "ru": "каша", "gender": "f", "audio": "../audio/каша.mp3" },
        { "ru": "картофель", "gender": "m", "audio": "../audio/картофель.mp3" },
        { "ru": "помидор", "gender": "m", "audio": "../audio/помидор.mp3" },
        { "ru": "огурец", "gender": "m", "audio": "../audio/огурец.mp3" },
        { "ru": "морковь", "gender": "f", "audio": "../audio/морковь.mp3" },
        { "ru": "капуста", "gender": "f", "audio": "../audio/капуста.mp3" },
        { "ru": "шпинат", "gender": "m", "audio": "../audio/шпинат.mp3" },
        { "ru": "салат", "gender": "m", "audio": "../audio/салат.mp3" },
        { "ru": "тыква", "gender": "f", "audio": "../audio/тыква.mp3" },
        { "ru": "свёкла", "gender": "f", "audio": "../audio/свёкла.mp3" },
        { "ru": "редис", "gender": "m", "audio": "../audio/редис.mp3" },
        { "ru": "кабачок", "gender": "m", "audio": "../audio/кабачок.mp3" },
        { "ru": "лук", "gender": "m", "audio": "../audio/лук.mp3" },
        { "ru": "чеснок", "gender": "m", "audio": "../audio/чеснок.mp3" },
        { "ru": "яблоко", "gender": "n", "audio": "../audio/яблоко.mp3" },
        { "ru": "груша", "gender": "f", "audio": "../audio/груша.mp3" },
        { "ru": "вишня", "gender": "f", "audio": "../audio/вишня.mp3" },
        { "ru": "клубника", "gender": "f", "audio": "../audio/клубника.mp3" },
        { "ru": "виноград", "gender": "m", "audio": "../audio/виноград.mp3" },
        { "ru": "арбуз", "gender": "m", "audio": "../audio/арбуз.mp3" },
        { "ru": "банан", "gender": "m", "audio": "../audio/банан.mp3" },
        { "ru": "инжир", "gender": "m", "audio": "../audio/инжир.mp3" },
        { "ru": "ананас", "gender": "m", "audio": "../audio/ананас.mp3" },
        { "ru": "киви", "gender": "n", "audio": "../audio/киви.mp3" },
        { "ru": "апельсин", "gender": "m", "audio": "../audio/апельсин.mp3" },
        { "ru": "лимон", "gender": "m", "audio": "../audio/лимон.mp3" },
        { "ru": "десерт", "gender": "m", "audio": "../audio/десерт.mp3" },
        { "ru": "мёд", "gender": "m", "audio": "../audio/мёд.mp3" },
        { "ru": "пирог", "gender": "m", "audio": "../audio/пирог.mp3" },
        { "ru": "торт", "gender": "m", "audio": "../audio/торт.mp3" },
        { "ru": "шоколад", "gender": "m", "audio": "../audio/шоколад.mp3" },
        { "ru": "печенье", "gender": "n", "audio": "../audio/печенье.mp3" },
        { "ru": "мороженое", "gender": "n", "audio": "../audio/мороженое.mp3" },
        { "ru": "соль", "gender": "f", "audio": "../audio/соль.mp3" },
        { "ru": "сахар", "gender": "m", "audio": "../audio/сахар.mp3" },
        { "ru": "перец", "gender": "m", "audio": "../audio/перец.mp3" },
        { "ru": "корица", "gender": "f", "audio": "../audio/корица.mp3" },
        { "ru": "куркума", "gender": "f", "audio": "../audio/куркума.mp3" },
        { "ru": "мята", "gender": "f", "audio": "../audio/мята.mp3" },
        { "ru": "фундук", "gender": "m", "audio": "../audio/фундук.mp3" },
        { "ru": "изюм", "gender": "m", "audio": "../audio/изюм.mp3" },
        { "ru": "алкоголь", "gender": "m", "audio": "../audio/алкоголь.mp3" },
        { "ru": "вино", "gender": "n", "audio": "../audio/вино.mp3" },
        { "ru": "пиво", "gender": "n", "audio": "../audio/пиво.mp3" },


        { "ru": "учёба", "gender": "f", "audio": "../audio/учёба.mp3" },
        { "ru": "учебник", "gender": "m", "audio": "../audio/учебник.mp3" },
        { "ru": "словарь", "gender": "m", "audio": "../audio/словарь.mp3" },
        { "ru": "профессия", "gender": "f", "audio": "../audio/профессия.mp3" },
        { "ru": "специальность", "gender": "f", "audio": "../audio/специальность.mp3" },
        { "ru": "школа", "gender": "f", "audio": "../audio/школа.mp3" },
        { "ru": "университет", "gender": "m", "audio": "../audio/университет.mp3" },
        { "ru": "учитель", "gender": "m", "audio": "../audio/учитель.mp3" },
        { "ru": "профессор", "gender": "m", "audio": "../audio/профессор.mp3" },
        { "ru": "учёный", "gender": "m", "audio": "../audio/учёный.mp3" },
        { "ru": "врач", "gender": "m", "audio": "../audio/врач.mp3" },
        { "ru": "инженер", "gender": "m", "audio": "../audio/инженер.mp3" },
        { "ru": "адвокат", "gender": "m", "audio": "../audio/адвокат.mp3" },
        { "ru": "медсестра", "gender": "f", "audio": "../audio/медсестра.mp3" },
        { "ru": "продавец", "gender": "m", "audio": "../audio/продавец.mp3" },
       


        { "ru": "путешествие", "gender": "n", "audio": "../audio/путешествие.mp3" },
        { "ru": "путешественник", "gender": "m", "audio": "../audio/путешественник.mp3" },
        { "ru": "поездка", "gender": "f", "audio": "../audio/поездка.mp3" },
        { "ru": "туризм", "gender": "m", "audio": "../audio/туризм.mp3" },
        { "ru": "турист", "gender": "m", "audio": "../audio/турист.mp3" },
        { "ru": "экскурсовод", "gender": "m", "audio": "../audio/экскурсовод.mp3" },
        { "ru": "экскурсия", "gender": "f", "audio": "../audio/экскурсия.mp3" },
        { "ru": "информация", "gender": "f", "audio": "../audio/информация.mp3" },
        { "ru": "карта", "gender": "f", "audio": "../audio/карта.mp3" },
        { "ru": "кошелёк", "gender": "m", "audio": "../audio/кошелёк.mp3" },
        { "ru": "паспорт", "gender": "m", "audio": "../audio/паспорт.mp3" },
        { "ru": "виза", "gender": "f", "audio": "../audio/виза.mp3" },
        { "ru": "страховка", "gender": "f", "audio": "../audio/страховка.mp3" },
        { "ru": "цена", "gender": "f", "audio": "../audio/цена.mp3" },
        { "ru": "распродажа", "gender": "f", "audio": "../audio/распродажа.mp3" },
        { "ru": "скидка", "gender": "f", "audio": "../audio/скидка.mp3" },
        { "ru": "посольство", "gender": "n", "audio": "../audio/посольство.mp3" },
        { "ru": "консульство", "gender": "n", "audio": "../audio/консульство.mp3" },
        { "ru": "полиция", "gender": "f", "audio": "../audio/полиция.mp3" },
        { "ru": "билет", "gender": "m", "audio": "../audio/билет.mp3" },
        { "ru": "гостиница", "gender": "f", "audio": "../audio/гостиница.mp3" },
        { "ru": "номер", "gender": "m", "audio": "../audio/номер.mp3" },
        { "ru": "бронь", "gender": "f", "audio": "../audio/бронь.mp3" },
        { "ru": "рейс", "gender": "m", "audio": "../audio/рейс.mp3" },
        { "ru": "транзит", "gender": "m", "audio": "../audio/транзит.mp3" },
        { "ru": "вход", "gender": "m", "audio": "../audio/вход.mp3" },
        { "ru": "выход", "gender": "m", "audio": "../audio/выход.mp3" },
        { "ru": "таможня", "gender": "f", "audio": "../audio/таможня.mp3" },
        { "ru": "контроль", "gender": "m", "audio": "../audio/контроль.mp3" },
        { "ru": "штамп", "gender": "m", "audio": "../audio/штамп.mp3" },
        { "ru": "сумка", "gender": "f", "audio": "../audio/сумка.mp3" },
        { "ru": "багаж", "gender": "m", "audio": "../audio/багаж.mp3" },
        { "ru": "дорога", "gender": "f", "audio": "../audio/дорога.mp3" },
        { "ru": "тротуар", "gender": "m", "audio": "../audio/тротуар.mp3" },
        { "ru": "транспорт", "gender": "m", "audio": "../audio/транспорт.mp3" },
        { "ru": "пассажир", "gender": "m", "audio": "../audio/пассажир.mp3" },
        { "ru": "велосипед", "gender": "m", "audio": "../audio/велосипед.mp3" },
        { "ru": "машина", "gender": "f", "audio": "../audio/машина.mp3" },
        { "ru": "автобус", "gender": "m", "audio": "../audio/автобус.mp3" },
        { "ru": "автовокзал", "gender": "m", "audio": "../audio/автовокзал.mp3" },
        { "ru": "вертолёт", "gender": "m", "audio": "../audio/вертолёт.mp3" },
        { "ru": "самолёт", "gender": "m", "audio": "../audio/самолёт.mp3" },
        { "ru": "аэропорт", "gender": "m", "audio": "../audio/аэропорт.mp3" },
        { "ru": "поезд", "gender": "m", "audio": "../audio/поезд.mp3" },
        { "ru": "метро", "gender": "n", "audio": "../audio/метро.mp3" },
        { "ru": "лодка", "gender": "f", "audio": "../audio/лодка.mp3" },
        { "ru": "яхта", "gender": "f", "audio": "../audio/яхта.mp3" },
        { "ru": "корабль", "gender": "m", "audio": "../audio/корабль.mp3" },
        { "ru": "порт", "gender": "m", "audio": "../audio/порт.mp3" },
        { "ru": "праздник", "gender": "m", "audio": "../audio/праздник.mp3" },
        { "ru": "погода", "gender": "f", "audio": "../audio/погода.mp3" },
        { "ru": "небо", "gender": "n", "audio": "../audio/небо.mp3" },
        { "ru": "земля", "gender": "f", "audio": "../audio/земля.mp3" },
        { "ru": "огонь", "gender": "m", "audio": "../audio/огонь.mp3" },
        { "ru": "воздух", "gender": "m", "audio": "../audio/воздух.mp3" },
        { "ru": "солнце", "gender": "n", "audio": "../audio/солнце.mp3" },
        { "ru": "луна", "gender": "f", "audio": "../audio/луна.mp3" },
        { "ru": "звезда", "gender": "f", "audio": "../audio/звезда.mp3" },
        { "ru": "дождь", "gender": "m", "audio": "../audio/дождь.mp3" },
        { "ru": "ветер", "gender": "m", "audio": "../audio/ветер.mp3" },
        { "ru": "град", "gender": "m", "audio": "../audio/град.mp3" },
        { "ru": "снег", "gender": "m", "audio": "../audio/снег.mp3" },
        { "ru": "лёд", "gender": "m", "audio": "../audio/лёд.mp3" },
        { "ru": "ураган", "gender": "m", "audio": "../audio/ураган.mp3" },
        { "ru": "буря", "gender": "f", "audio": "../audio/буря.mp3" },
        { "ru": "землетрясение", "gender": "n", "audio": "../audio/землетрясение.mp3" },
        { "ru": "море", "gender": "n", "audio": "../audio/море.mp3" },
        { "ru": "река", "gender": "f", "audio": "../audio/река.mp3" },
        { "ru": "озеро", "gender": "n", "audio": "../audio/озеро.mp3" },
        { "ru": "остров", "gender": "m", "audio": "../audio/остров.mp3" },
        { "ru": "водопад", "gender": "m", "audio": "../audio/водопад.mp3" },
        { "ru": "пещера", "gender": "f", "audio": "../audio/пещера.mp3" },
        { "ru": "пляж", "gender": "m", "audio": "../audio/пляж.mp3" },
        { "ru": "пустыня", "gender": "f", "audio": "../audio/пустыня.mp3" },
        { "ru": "лес", "gender": "m", "audio": "../audio/лес.mp3" },
        { "ru": "гора", "gender": "f", "audio": "../audio/гора.mp3" },
        { "ru": "вулкан", "gender": "m", "audio": "../audio/вулкан.mp3" },
        { "ru": "камень", "gender": "m", "audio": "../audio/камень.mp3" },
        { "ru": "авария", "gender": "f", "audio": "../audio/авария.mp3" },
        { "ru": "больница", "gender": "f", "audio": "../audio/больница.mp3" },
        { "ru": "ресторан", "gender": "m", "audio": "../audio/ресторан.mp3" },
        { "ru": "кафе", "gender": "n", "audio": "../audio/кафе.mp3" },
        { "ru": "рынок", "gender": "m", "audio": "../audio/рынок.mp3" },
        { "ru": "магазин", "gender": "m", "audio": "../audio/магазин.mp3" },
        { "ru": "тюрьма", "gender": "f", "audio": "../audio/тюрьма.mp3" },
        { "ru": "музей", "gender": "m", "audio": "../audio/музей.mp3" },
        { "ru": "стадион", "gender": "m", "audio": "../audio/стадион.mp3" },
        { "ru": "концерт", "gender": "m", "audio": "../audio/концерт.mp3" },
        { "ru": "сувенир", "gender": "m", "audio": "../audio/сувенир.mp3" },
        { "ru": "подарок", "gender": "m", "audio": "../audio/подарок.mp3" },
        { "ru": "кальян", "gender": "m", "audio": "../audio/кальян.mp3" },
        { "ru": "золото", "gender": "n", "audio": "../audio/золото.mp3" },
        { "ru": "серебро", "gender": "n", "audio": "../audio/серебро.mp3" },
        { "ru": "платина", "gender": "f", "audio": "../audio/платина.mp3" },
        { "ru": "север", "gender": "m", "audio": "../audio/север.mp3" },
        { "ru": "юг", "gender": "m", "audio": "../audio/юг.mp3" },
        { "ru": "запад", "gender": "m", "audio": "../audio/запад.mp3" },
        { "ru": "восток", "gender": "m", "audio": "../audio/восток.mp3" },
        { "ru": "страна", "gender": "f", "audio": "../audio/страна.mp3" },
        { "ru": "город", "gender": "m", "audio": "../audio/город.mp3" },
        { "ru": "столица", "gender": "f", "audio": "../audio/столица.mp3" },
        { "ru": "деревня", "gender": "f", "audio": "../audio/деревня.mp3" },
        { "ru": "Россия", "gender": "f", "audio": "../audio/Россия.mp3" },
        { "ru": "Москва", "gender": "f", "audio": "../audio/Москва.mp3" },
        { "ru": "Санкт‑Петербург", "gender": "m", "audio": "../audio/Санкт-Петербург.mp3" },
        { "ru": "Иордания", "gender": "f", "audio": "../audio/Иордания.mp3" },
        { "ru": "Ирак", "gender": "m", "audio": "../audio/Ирак.mp3" },
        { "ru": "Багдад", "gender": "m", "audio": "../audio/Багдад.mp3" },
        { "ru": "Сирия", "gender": "f", "audio": "../audio/Сирия.mp3" },
        { "ru": "Дамаск", "gender": "m", "audio": "../audio/Дамаск.mp3" }




    ];

    const genders = [
        { id: "m", label: "المذكر" },
        { id: "f", label: "المؤنث" },
        { id: "n", label: "المفرد" }
    ];

    let correctWord = null;
    let hasAnswered = false;
    let correctCount = 0;
    let wrongCount = 0;

    const wordButton = document.getElementById("word-button");
    const optionsContainer = document.getElementById("options");
    const resultBox = document.getElementById("result");
    const scoreBox = document.getElementById("score");

    const nextButton = document.createElement("button");
    nextButton.textContent = "🌿 التالي";
    nextButton.className = "next-button";

    nextButton.onclick = () => {
        renderQuestion();
        nextButton.style.display = "none";
        hasAnswered = false;
    };
    document.getElementById("next-button-container").appendChild(nextButton);

    function updateScore() {
        scoreBox.textContent = `✅: ${correctCount} | ❌: ${wrongCount}`;
    }

    function getRandomWord() {
        return words[Math.floor(Math.random() * words.length)];
    }

    function renderQuestion() {
        correctWord = getRandomWord();
        resultBox.textContent = "";
        optionsContainer.innerHTML = "";

        wordButton.textContent = correctWord.ru;
        wordButton.onclick = () => {
            new Audio(correctWord.audio).play();
        };

        genders.forEach(g => {
            const btn = document.createElement("button");
            btn.textContent = g.label;
            btn.lang = "ar";
            btn.onclick = () => checkAnswer(g.id);
            optionsContainer.appendChild(btn);
        });
    }

    function checkAnswer(selectedGender) {
        if (hasAnswered) return;
        hasAnswered = true;
    
        document
            .querySelectorAll("#options button")
            .forEach(b => b.disabled = true);
    
        const correctLabel = genders.find(g => g.id === correctWord.gender).label;
    
        if (selectedGender === correctWord.gender) {
            resultBox.textContent = "✅ صح";
            resultBox.style.color = "green";
            correctCount++;
        } else {
            resultBox.innerHTML =
                `<span dir="rtl" lang="ar">❌ خطأ. الإجابة الصحيحة: ${correctLabel}</span>`;
            resultBox.style.color = "red";
            wrongCount++;
        }
    
        updateScore();
        nextButton.style.display = "inline-block";
    }
    

    renderQuestion();
    updateScore();
};
